import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const script = await readFile(new URL('../start-safe-copy.ps1', import.meta.url), 'utf8');
const command = await readFile(new URL('../start-safe-copy.cmd', import.meta.url), 'utf8');
const adminLauncher = await readFile(new URL('../open-admin.ps1', import.meta.url), 'utf8');
const shortcutInstaller = await readFile(new URL('../scripts/install-safe-copy-shortcut.ps1', import.meta.url), 'utf8');

test('safe-copy launcher refuses production and derives LAN URL at runtime', () => {
  assert.match(script, /WARUN_ENV = 'safe-copy'/);
  assert.match(script, /SafeCopiesRoot/);
  assert.match(script, /Refusing the production DB path/);
  assert.match(script, /Get-LanIPv4/);
  assert.match(script, /X-Warun-Database-Target/);
  assert.match(script, /healthBody\.schemaVersion -ne \$TargetSchemaVersion/);
  assert.match(script, /Test-SupportedSafeCopySchema/);
  assert.match(script, /TargetSchemaVersion = 10/);
  assert.match(script, /SchemaVersion -eq \$TargetSchemaVersion -or \$SchemaVersion -eq \(\$TargetSchemaVersion - 1\)/);
  assert.match(script, /migrationRequired = \(\$schemaVersion -eq \(\$TargetSchemaVersion - 1\)\)/);
  assert.match(script, /migration required \(schema v\$\(\$TargetSchemaVersion - 1\) -> v\$TargetSchemaVersion\)/);
  assert.match(script, /AdminTokenPath/);
  assert.match(script, /Read-SafeCopyAdminToken/);
  assert.match(script, /KitchenTokenPath/);
  assert.match(script, /Read-SafeCopyKitchenToken/);
  assert.match(script, /provision-safe-copy-kitchen-token\.mjs/);
  assert.match(script, /Invoke-SafeCopyKitchenTokenOperation -Mode 'check'/);
  assert.match(script, /Invoke-SafeCopyKitchenTokenOperation -Mode 'ensure'/);
  assert.match(script, /safe-copy kitchen token check\/provision failed; startup was stopped/);
  assert.match(script, /WARUN_KITCHEN_API_TOKEN = \$SafeCopyKitchenToken/);
  assert.match(script, /Assert-SafeCopyInjectedKitchenToken/);
  assert.match(script, /Get-AdminPreflight/);
  assert.match(script, /WARUN_ADMIN_API_TOKEN = \$SafeCopyAdminToken/);
  assert.match(script, /PairingDiagnosticLogPath/);
  assert.match(script, /WARUN_PAIRING_DIAGNOSTIC_LOG_PATH = \$PairingDiagnosticLogPath/);
  assert.match(script, /CommunicationDiagnosticLogPath/);
  assert.match(script, /WARUN_COMMUNICATION_DIAGNOSTIC_LOG_PATH = \$CommunicationDiagnosticLogPath/);
  assert.match(script, /EnableMenuDiagnostics/);
  assert.match(script, /WARUN_MENU_DIAGNOSTIC_ENABLED/);
  assert.match(script, /WARUN_MENU_DIAGNOSTIC_LOG_PATH/);
  assert.match(script, /menuDiagnosticEnabled/);
  assert.match(script, /safe-copy admin preflight did not return HTTP 200/);
  assert.match(script, /ValidateSet\('start', 'stop', 'status'\)/);
  assert.match(script, /\[string\]\$RuntimeRoot/);
  assert.match(script, /\[string\]\$WebRoot/);
  assert.match(script, /Read-RuntimeState/);
  assert.match(script, /Write-AtomicRuntimeState/);
  assert.match(script, /\[IO\.File\]::Replace/);
  assert.match(script, /\.runtime-state-.*NewGuid/);
  assert.match(script, /Test-ExistingRuntime/);
  assert.match(script, /Get-ProcessSnapshot/);
  assert.match(script, /src\[\\\\\/\]run-server\\\.mjs/);
  assert.match(script, /Invoke-RuntimeStop/);
  assert.match(script, /Remove-RuntimeStateIfUnchanged/);
  assert.match(script, /Refusing to remove runtime-state because it changed/);
  assert.match(script, /Runtime-state conflict/);
  assert.match(script, /runtime-state\.json is invalid/);
  assert.doesNotMatch(script, /\$StatePath.*Set-Content/);
  assert.match(script, /\$MutexAlreadyHeld/);
  assert.match(script, /WarunTabOrder\.SafeCopy\.AdminLauncher/);
  assert.match(script, /AbandonedMutexException/);
  assert.match(script, /ReleaseMutex/);
  assert.match(script, /finally/);
  assert.doesNotMatch(script, /192\\.168\\.1\\./);

  assert.match(adminLauncher, /\[string\]\$ProjectRoot/);
  assert.match(adminLauncher, /Start-Process -FilePath 'powershell\.exe'/);
  assert.match(adminLauncher, /TargetSchemaVersion = 10/);
  assert.match(adminLauncher, /schemaVersion -eq \$TargetSchemaVersion/);
  assert.match(adminLauncher, /ReleaseMutex/);
  assert.match(shortcutInstaller, /open-admin\.ps1/);
  assert.match(shortcutInstaller, /WriteAllText/);
  assert.match(shortcutInstaller, /CreateShortcut/);
  assert.match(shortcutInstaller, /-ProjectRoot/);
});

test('safe-copy command delegates to the dedicated script', () => {
  assert.match(command, /start-safe-copy\.ps1/);
});
